import createClient from 'openapi-fetch';
import type { paths } from './schema.d.ts'; // generated by openapi-typescript

/**
 * Type-safe REST client for the OmniVerse Vision backend.
 */
export const client = createClient<paths>({
  baseUrl: 'http://localhost:8000',
});

// Helper for type-safe endpoints
export type Client = typeof client;
