/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/frame": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Frame */
        get: operations["get_frame_api_v1_frame_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Result */
        get: operations["get_run_result_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Run */
        post: operations["export_run_api_v1_runs__run_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/doctor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Doctor */
        get: operations["run_doctor_api_v1_doctor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Skills */
        get: operations["list_skills_api_v1_skills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills/{skill}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Skill */
        post: operations["run_skill_api_v1_skills__skill__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tools */
        get: operations["tools_api_v1_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Probe */
        get: operations["probe_api_v1_probe_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve Platform */
        get: operations["resolve_platform_api_v1_platform_resolve_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Build Plan */
        post: operations["build_plan_api_v1_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent Tasks */
        get: operations["recent_tasks_api_v1_tasks_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_api_v1_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task Events */
        get: operations["get_task_events_api_v1_tasks__task_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task Status */
        get: operations["get_task_status_api_v1_tasks__task_id__get"];
        put?: never;
        post?: never;
        /** Cancel Task */
        delete: operations["cancel_task_api_v1_tasks__task_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Task */
        post: operations["retry_task_api_v1_tasks__task_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Task Errors */
        get: operations["list_task_errors_api_v1_tasks_errors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/subtitle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Subtitle
         * @description Ingest subtitle from Browser Clipper to bypass backend fetching.
         */
        post: operations["ingest_subtitle_api_v1_ingest_subtitle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/cookie": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Cookie
         * @description Ingest fresh cookies from the browser to rescue failed backend downloads.
         */
        post: operations["ingest_cookie_api_v1_ingest_cookie_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/ui-capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Ui Capture
         * @description Ingest a browser/host screenshot into trusted ui_captures for Agent review.
         */
        post: operations["ingest_ui_capture_api_v1_ingest_ui_capture_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/dynamic-capture-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Dynamic Capture Plan
         * @description Return a backend-owned dynamic webpage capture plan for browser agents.
         */
        post: operations["create_dynamic_capture_plan_api_v1_ingest_dynamic_capture_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/dynamic-ui-capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Dynamic Ui Capture
         * @description Ingest bounded scroll/animation screenshots captured by Backend Browser Agent.
         */
        post: operations["ingest_dynamic_ui_capture_api_v1_ingest_dynamic_ui_capture_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingest/web-evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Web Evidence
         * @description Ingest browser-visible webpage evidence for text-only agents.
         */
        post: operations["ingest_web_evidence_api_v1_ingest_web_evidence_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/intake": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agent Intake */
        post: operations["agent_intake_api_v1_agent_intake_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/preflight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agent Preflight */
        post: operations["agent_preflight_api_v1_agent_preflight_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/browser-agent/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Browser Agent Evidence
         * @description Store backend browser-agent evidence under the source asset directory.
         */
        post: operations["ingest_browser_agent_evidence_api_v1_browser_agent_evidence_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/browser-agent/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Browser Agent Status */
        get: operations["get_browser_agent_status_api_v1_browser_agent_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentIntakeRequest */
        AgentIntakeRequest: {
            /**
             * Message
             * @default
             */
            message: string;
            /** Attachments */
            attachments?: unknown[];
            /** Capability Profile */
            capability_profile?: {
                [key: string]: unknown;
            } | null;
            /**
             * Skill
             * @default
             */
            skill: string;
            /**
             * Depth
             * @default text_only
             */
            depth: string;
        };
        /** AgentPreflightRequest */
        AgentPreflightRequest: {
            /**
             * Message
             * @default
             */
            message: string;
            /** Attachments */
            attachments?: unknown[];
            /** Capability Profile */
            capability_profile?: {
                [key: string]: unknown;
            } | null;
            /**
             * Skill
             * @default note
             */
            skill: string;
            /**
             * Depth
             * @default text_only
             */
            depth: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /** Source */
            source: string;
            /**
             * Skill
             * @default video-note
             */
            skill: string;
            /**
             * Depth
             * @default text_only
             */
            depth: string;
            /** Options */
            options?: {
                [key: string]: unknown;
            };
            client_provided?: components["schemas"]["ClientProvidedInput"] | null;
        };
        /** BrowserAgentCookie */
        BrowserAgentCookie: {
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Domain
             * @default
             */
            domain: string;
            /**
             * Path
             * @default
             */
            path: string;
            /** Secure */
            secure?: boolean | null;
            /** Httponly */
            httpOnly?: boolean | null;
            /** Samesite */
            sameSite?: string | null;
            /** Expires */
            expires?: number | null;
            /** Value */
            value?: string | null;
        };
        /** BrowserAgentEvidenceRequest */
        BrowserAgentEvidenceRequest: {
            /**
             * Schema Version
             * @default omniverse.browser_agent_evidence.v1
             * @constant
             */
            schema_version: "omniverse.browser_agent_evidence.v1";
            /** Source Url */
            source_url: string;
            /** Canonical Url */
            canonical_url?: string | null;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Platform
             * @default unknown
             */
            platform: string;
            /** Captured At Ms */
            captured_at_ms?: number | null;
            /**
             * Page Markdown
             * @default
             */
            page_markdown: string;
            /**
             * Clean Text
             * @default
             */
            clean_text: string;
            /** Code Blocks */
            code_blocks?: {
                [key: string]: unknown;
            }[];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Links */
            links?: {
                [key: string]: unknown;
            }[];
            /** Images */
            images?: {
                [key: string]: unknown;
            }[];
            /** Media */
            media?: {
                [key: string]: unknown;
            };
            /** Subtitle Tracks */
            subtitle_tracks?: {
                [key: string]: unknown;
            }[];
            /** Subtitles */
            subtitles?: {
                [key: string]: unknown;
            }[];
            /** Chapters */
            chapters?: {
                [key: string]: unknown;
            }[];
            /** Danmaku */
            danmaku?: {
                [key: string]: unknown;
            }[];
            /** Comments */
            comments?: {
                [key: string]: unknown;
            }[];
            /** Download Candidates */
            download_candidates?: {
                [key: string]: unknown;
            }[];
            /** Cookie Metadata */
            cookie_metadata?: components["schemas"]["BrowserAgentCookie"][];
            /** Raw Cookies */
            raw_cookies?: components["schemas"]["BrowserAgentCookie"][];
            /** Screenshot Data Url */
            screenshot_data_url?: string | null;
            /** Viewport */
            viewport?: {
                [key: string]: unknown;
            };
            /** Capabilities */
            capabilities?: {
                [key: string]: unknown;
            };
        };
        /** ChatAttachment */
        ChatAttachment: {
            /** Type */
            type: string;
            /** Description */
            description: string;
        };
        /** ChatMessage */
        ChatMessage: {
            /** Role */
            role: string;
            /** Content */
            content: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Question */
            question: string;
            /** Source Hash */
            source_hash: string;
            /** History */
            history?: components["schemas"]["ChatMessage"][];
            /** Attachments */
            attachments?: components["schemas"]["ChatAttachment"][];
        };
        /** ClientProvidedInput */
        ClientProvidedInput: {
            subtitle?: components["schemas"]["ClientProvidedSubtitleInput"] | null;
        };
        /** ClientProvidedSubtitleInput */
        ClientProvidedSubtitleInput: {
            /** Content */
            content: string;
            /**
             * Format
             * @default srt
             */
            format: string;
            /**
             * Language
             * @default zh-Hans
             */
            language: string;
            /**
             * Source
             * @default browser_clipper
             */
            source: string;
        };
        /** CookieIngestRequest */
        CookieIngestRequest: {
            /** Platform */
            platform: string;
            /** Cookie String */
            cookie_string: string;
        };
        /** DynamicCaptureFrame */
        DynamicCaptureFrame: {
            /** Sequence */
            sequence: number;
            /**
             * Kind
             * @default scroll_section
             */
            kind: string;
            /**
             * Label
             * @default
             */
            label: string;
            /** Data Url */
            data_url: string;
            /** Captured At Ms */
            captured_at_ms?: number | null;
            /** Viewport */
            viewport?: {
                [key: string]: number;
            };
            /** Scroll */
            scroll?: {
                [key: string]: number | string;
            };
            /** Wait Ms */
            wait_ms?: number | null;
            /** Notes */
            notes?: string[];
        };
        /** DynamicCaptureIngestRequest */
        DynamicCaptureIngestRequest: {
            /** Source Url */
            source_url: string;
            /** Canonical Url */
            canonical_url?: string | null;
            /**
             * Capture Id
             * @default
             */
            capture_id: string;
            /** Plan */
            plan?: {
                [key: string]: unknown;
            };
            /** Frames */
            frames?: components["schemas"]["DynamicCaptureFrame"][];
            /** Overlay Actions */
            overlay_actions?: {
                [key: string]: unknown;
            }[];
            /** Human Escalations */
            human_escalations?: {
                [key: string]: unknown;
            }[];
            /** Recording */
            recording?: {
                [key: string]: unknown;
            };
            /** Execution */
            execution?: {
                [key: string]: unknown;
            };
            /** Errors */
            errors?: {
                [key: string]: unknown;
            }[];
        };
        /** DynamicCapturePlanRequest */
        DynamicCapturePlanRequest: {
            /** Source Url */
            source_url: string;
            /**
             * Mode
             * @default balanced
             */
            mode: string;
            /** Hardware Profile */
            hardware_profile?: {
                [key: string]: unknown;
            };
        };
        /** ExportRequest */
        ExportRequest: {
            /** Provider */
            provider: string;
            /**
             * Title
             * @default OmniVerse Vision Export
             */
            title: string;
            /** Options */
            options?: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PlanRequest */
        PlanRequest: {
            /** Url */
            url: string;
            /**
             * Skill
             * @default video-note
             */
            skill: string;
            /**
             * Depth
             * @default text_only
             */
            depth: string;
            /** Metadata */
            metadata?: unknown | null;
            /** Capability Profile */
            capability_profile?: {
                [key: string]: unknown;
            } | null;
        };
        /** SkillRunRequest */
        SkillRunRequest: {
            /** Url */
            url: string;
            /**
             * Depth
             * @default text_only
             */
            depth: string;
        };
        /** SkillRunResponse */
        SkillRunResponse: {
            /**
             * Source Hash
             * @default
             */
            source_hash: string;
            /**
             * Skill
             * @default
             */
            skill: string;
            /**
             * Skill Prompt
             * @default
             */
            skill_prompt: string;
            /**
             * Transcript
             * @default
             */
            transcript: string;
            /** Frames */
            frames?: {
                [key: string]: unknown;
            }[];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Errors */
            errors?: string[];
        };
        /** SubtitleIngestRequest */
        SubtitleIngestRequest: {
            /** Source Url */
            source_url: string;
            /**
             * Format
             * @default srt
             */
            format: string;
            /**
             * Language
             * @default zh
             */
            language: string;
            /** Content */
            content: string;
        };
        /** UiCaptureIngestRequest */
        UiCaptureIngestRequest: {
            /**
             * Source Url
             * @default
             */
            source_url: string;
            /** Data Url */
            data_url: string;
            /**
             * Target Kind
             * @default browser
             */
            target_kind: string;
            /**
             * Purpose
             * @default agent_visual_evidence
             */
            purpose: string;
            /** Captured At Ms */
            captured_at_ms?: number | null;
            /** Viewport */
            viewport?: {
                [key: string]: number;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WebEvidenceIngestRequest */
        WebEvidenceIngestRequest: {
            /** Source Url */
            source_url: string;
            /** Canonical Url */
            canonical_url?: string | null;
            /**
             * Title
             * @default
             */
            title: string;
            /** Captured At Ms */
            captured_at_ms?: number | null;
            /**
             * Page Markdown
             * @default
             */
            page_markdown: string;
            /**
             * Text Excerpt
             * @default
             */
            text_excerpt: string;
            /**
             * Selection
             * @default
             */
            selection: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Links */
            links?: {
                [key: string]: string;
            }[];
            /** Images */
            images?: {
                [key: string]: string;
            }[];
            /** Viewport */
            viewport?: {
                [key: string]: number;
            };
            /** Media Evidence */
            media_evidence?: {
                [key: string]: unknown;
            } | null;
            /** Processing Hints */
            processing_hints?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_frame_api_v1_frame_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_result_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_run_api_v1_runs__run_id__export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_doctor_api_v1_doctor_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_skills_api_v1_skills_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
        };
    };
    run_skill_api_v1_skills__skill__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skill: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tools_api_v1_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    chat_api_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_get: {
        parameters: {
            query: {
                q: string;
                source_hash?: string;
                top_k?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    probe_api_v1_probe_get: {
        parameters: {
            query: {
                url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_platform_api_v1_platform_resolve_get: {
        parameters: {
            query: {
                source: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_plan_api_v1_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recent_tasks_api_v1_tasks_recent_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_api_v1_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_events_api_v1_tasks__task_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_status_api_v1_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_task_api_v1_tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_task_api_v1_tasks__task_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_task_errors_api_v1_tasks_errors_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_subtitle_api_v1_ingest_subtitle_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubtitleIngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_cookie_api_v1_ingest_cookie_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CookieIngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_ui_capture_api_v1_ingest_ui_capture_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UiCaptureIngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_dynamic_capture_plan_api_v1_ingest_dynamic_capture_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DynamicCapturePlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_dynamic_ui_capture_api_v1_ingest_dynamic_ui_capture_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DynamicCaptureIngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_web_evidence_api_v1_ingest_web_evidence_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebEvidenceIngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_intake_api_v1_agent_intake_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentIntakeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_preflight_api_v1_agent_preflight_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentPreflightRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_browser_agent_evidence_api_v1_browser_agent_evidence_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrowserAgentEvidenceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_browser_agent_status_api_v1_browser_agent_status_get: {
        parameters: {
            query: {
                source: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
