/**
 * The main window's layout, as a tree.
 *
 * Fleet's shell could only ever express one thing: a navigation state that
 * shows a list. `AppShell.tsx` grew to 4,000 lines of
 * `if (isSourcesNavigation) … if (isSkillsNavigation) …`, each branch naming a
 * concrete surface, and `PanelStackContainer` derived its panels from the
 * route. Every new surface therefore had to become a navigation state plus a
 * sidebar row — which is why asking for an infinite canvas kept producing
 * another second-level page.
 *
 * This is the seam that was missing. A layout is a tree of panes; a pane says
 * only which `panelKind` it hosts; a registry maps kind to component. The
 * engine never learns who the panels are. Adding the canvas, the browser, the
 * document editor or the video timeline is one registry entry and one pane —
 * the engine does not change, and neither does this file.
 *
 * It lives in `shared` because the renderer draws the tree and the main process
 * validates it before writing it to disk. Two implementations of "is this
 * layout legal" would drift, and the one that drifts is the one that lets a
 * corrupt file through.
 *
 * Zero dependencies, zero IO, every function pure, no input ever mutated, and
 * nothing here throws — a damaged layout coerces back to the default instead.
 * That is what makes "the file got corrupted, restart fixed it" true.
 *
 * The model follows Cindy's `shared/layoutTree.ts` (Apache-2.0), which solved
 * this problem first; see `docs/references/REFERENCE-REGISTRY.md`.
 */

/** Schema version of a persisted layout. Bump only with a migration. */
export const LAYOUT_SCHEMA_VERSION = 1 as const

/**
 * Maximum depth of the split tree, leaves included. A corrupt or hostile file
 * must not be able to blow the render stack.
 */
export const MAX_TREE_DEPTH = 8

/** Longest accepted `panelKind`. Anything longer is treated as corruption. */
const MAX_PANEL_KIND_LENGTH = 128

/**
 * Smallest share a split child may hold. A resize that would push a sibling
 * below this is rejected whole rather than clamped, so a drag either lands or
 * springs back — it never silently produces a pane too narrow to use.
 */
export const MIN_SPLIT_CHILD_FRACTION = 0.05

/**
 * Comparison slack for fractions. A caller that clamps to the floor computes a
 * value carrying float residue (`0.4589135 - 0.05` added back is
 * `0.04999999999999999`), and a bare `< 0.05` test would reject the very
 * transfer that was clamped correctly — the drag would spring back at exactly
 * the boundary the clamp was meant to reach.
 */
const FRACTION_TOLERANCE = 1e-9

/**
 * The panes Fleet ships. Everything else — the production surfaces, plugin
 * panels — arrives through the open namespace below.
 */
export const BUILTIN_PANEL_KINDS = ['nav-sidebar', 'navigator', 'main', 'workbench'] as const
export type BuiltinPanelKind = (typeof BUILTIN_PANEL_KINDS)[number]

/**
 * A panel's identity.
 *
 * Deliberately an open namespace — any non-empty string — rather than a closed
 * union, and the reason is what happens when a kind is *not* recognised. A
 * surface that is not installed, or a kind added by a newer version, must leave
 * the tree **legal**: the renderer hides that pane and reflows the space, and
 * the pane comes back where it was when the surface returns. If an unknown kind
 * invalidated the tree instead, uninstalling one plugin would destroy the
 * person's entire layout.
 *
 * `(string & {})` keeps editor completion for the builtin names while accepting
 * any string.
 */
export type PanelKind = BuiltinPanelKind | (string & {})

/** A leaf: one docking position holding one panel. */
export type PaneNode = {
  type: 'pane'
  /** Unique within the layout. Generated by the caller — this layer stays deterministic. */
  id: string
  panelKind: PanelKind
  /**
   * Collapsed state. Whether a pane *may* collapse depends on it being against
   * an edge, which only the renderer knows; this field carries the state alone.
   */
  collapsed?: boolean
  /** Minimum width in px. */
  minWidth?: number
}

/** A cut in one direction. Each child's `fraction` is its share along that axis. */
export type SplitNode = {
  type: 'split'
  id: string
  /** `row` lays children out horizontally; `column` stacks them. */
  direction: 'row' | 'column'
  children: { fraction: number; node: LayoutNode }[]
}

export type LayoutNode = PaneNode | SplitNode

/** A free-floating panel. Reserved: v1 keeps this empty. */
export type FloatPanel = {
  id: string
  panelKind: PanelKind
  x: number
  y: number
  width: number
  height: number
}

/**
 * One layout for the window. It does not vary per session: panel *contents*
 * follow the session, the arrangement does not.
 */
export type Layout = {
  schemaVersion: typeof LAYOUT_SCHEMA_VERSION
  /**
   * The nav sidebar: a full-height column outside the tree, so no split inside
   * the content area can ever cut through it.
   */
  sidebar: PaneNode & { edge: 'left' }
  /** The content area. */
  content: LayoutNode
  /** Empty in v1. */
  float: FloatPanel[]
}

/** `ok: false` names the first violation — for logs, not for the person. */
export type ValidateResult = { ok: true } | { ok: false; reason: string }

/** `fallback: true` means the input was unusable and the default was returned. */
export type CoerceResult = { layout: Layout; fallback: boolean; reason?: string }

/** `applied: false` returns the original layout by reference, unchanged. */
export type LayoutOpResult = { layout: Layout; applied: boolean; reason?: string }

// ---------------------------------------------------------------------------
// Default
// ---------------------------------------------------------------------------

/**
 * The arrangement Fleet has today: the nav sidebar outside the tree, then the
 * navigator list, the main surface and the workbench side by side. The default
 * must reproduce what the person already sees, so mounting the engine changes
 * nothing visually on first run.
 */
export function createDefaultLayout(): Layout {
  return {
    schemaVersion: LAYOUT_SCHEMA_VERSION,
    sidebar: { type: 'pane', id: 'sidebar', panelKind: 'nav-sidebar', edge: 'left' },
    content: {
      type: 'split',
      id: 'root',
      direction: 'row',
      children: [
        { fraction: 0.24, node: { type: 'pane', id: 'navigator', panelKind: 'navigator', minWidth: 240 } },
        { fraction: 0.46, node: { type: 'pane', id: 'main', panelKind: 'main', minWidth: 400 } },
        { fraction: 0.3, node: { type: 'pane', id: 'workbench', panelKind: 'workbench', minWidth: 280 } },
      ],
    },
    float: [],
  }
}

// ---------------------------------------------------------------------------
// Guards and traversal
// ---------------------------------------------------------------------------

export function isPaneNode(node: LayoutNode): node is PaneNode {
  return node.type === 'pane'
}

export function isSplitNode(node: LayoutNode): node is SplitNode {
  return node.type === 'split'
}

function walkContentPanes(node: LayoutNode, out: PaneNode[]): void {
  if (node.type === 'pane') {
    out.push(node)
    return
  }
  for (const child of node.children) walkContentPanes(child.node, out)
}

/** Every pane: sidebar first, then the content tree depth-first, then floats. */
export function walkPanes(layout: Layout): PaneNode[] {
  const out: PaneNode[] = [layout.sidebar]
  walkContentPanes(layout.content, out)
  for (const f of layout.float) out.push({ type: 'pane', id: f.id, panelKind: f.panelKind })
  return out
}

export function findPaneById(layout: Layout, paneId: string): PaneNode | null {
  return walkPanes(layout).find((p) => p.id === paneId) ?? null
}

export function countPanelKind(layout: Layout, kind: PanelKind): number {
  return walkPanes(layout).filter((p) => p.panelKind === kind).length
}

/** Where a pane sits inside a split, for reading and writing its share. */
export interface SplitChildRef {
  splitId: string
  childIndex: number
  fraction: number
}

function findSplitChildByKindIn(node: LayoutNode, kind: PanelKind): SplitChildRef | null {
  if (node.type !== 'split') return null
  for (let i = 0; i < node.children.length; i++) {
    const child = node.children[i]
    if (!child) continue
    if (child.node.type === 'pane' && child.node.panelKind === kind) {
      return { splitId: node.id, childIndex: i, fraction: child.fraction }
    }
    const nested = findSplitChildByKindIn(child.node, kind)
    if (nested) return nested
  }
  return null
}

/**
 * Locate a panel by kind rather than by position, so a consumer that resizes
 * "the workbench" keeps working after the person moves it to the other side.
 */
export function findSplitChildByPanelKind(layout: Layout, kind: PanelKind): SplitChildRef | null {
  return findSplitChildByKindIn(layout.content, kind)
}

function findSplitById(node: LayoutNode, splitId: string): SplitNode | null {
  if (node.type !== 'split') return null
  if (node.id === splitId) return node
  for (const child of node.children) {
    const found = findSplitById(child.node, splitId)
    if (found) return found
  }
  return null
}

/** Rescale a split's children so the shares sum to exactly 1. */
function normalizeSplitFractions(split: SplitNode): void {
  const sum = split.children.reduce((acc, c) => acc + c.fraction, 0)
  if (sum <= 0) {
    const even = 1 / split.children.length
    for (const child of split.children) child.fraction = even
    return
  }
  for (const child of split.children) child.fraction = child.fraction / sum
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v)
}

function isValidId(v: unknown): v is string {
  return typeof v === 'string' && v.length > 0 && v.length <= 128
}

function isValidPanelKind(v: unknown): v is string {
  return typeof v === 'string' && v.length > 0 && v.length <= MAX_PANEL_KIND_LENGTH
}

/** Shape, depth and fractions for one node, collecting panes and ids as it goes. */
function validateNodeShape(
  node: unknown,
  depth: number,
  ids: Set<string>,
  panes: PaneNode[],
): ValidateResult {
  if (depth > MAX_TREE_DEPTH) return { ok: false, reason: `tree deeper than ${MAX_TREE_DEPTH}` }
  if (!isRecord(node)) return { ok: false, reason: 'node is not an object' }

  if (!isValidId(node.id)) return { ok: false, reason: 'node id invalid' }
  if (ids.has(node.id)) return { ok: false, reason: `duplicate node id: ${node.id}` }
  ids.add(node.id)

  if (node.type === 'pane') {
    if (!isValidPanelKind(node.panelKind)) return { ok: false, reason: 'panelKind invalid' }
    if (node.collapsed !== undefined && typeof node.collapsed !== 'boolean') {
      return { ok: false, reason: 'collapsed must be boolean' }
    }
    if (node.minWidth !== undefined && !(Number.isFinite(node.minWidth) && (node.minWidth as number) > 0)) {
      return { ok: false, reason: 'minWidth must be a positive finite number' }
    }
    panes.push(node as unknown as PaneNode)
    return { ok: true }
  }

  if (node.type === 'split') {
    if (node.direction !== 'row' && node.direction !== 'column') {
      return { ok: false, reason: 'split direction invalid' }
    }
    if (!Array.isArray(node.children) || node.children.length < 2) {
      return { ok: false, reason: 'split needs at least 2 children' }
    }
    let fractionSum = 0
    for (const child of node.children) {
      if (!isRecord(child)) return { ok: false, reason: 'split child is not an object' }
      if (!(Number.isFinite(child.fraction) && (child.fraction as number) > 0)) {
        return { ok: false, reason: 'child fraction must be a positive finite number' }
      }
      fractionSum += child.fraction as number
      const r = validateNodeShape(child.node, depth + 1, ids, panes)
      if (!r.ok) return r
    }
    if (Math.abs(fractionSum - 1) > 0.01) {
      return { ok: false, reason: `split fractions must sum to ~1, got ${fractionSum}` }
    }
    return { ok: true }
  }

  return { ok: false, reason: `unknown node type: ${String((node as { type?: unknown }).type)}` }
}

/**
 * Check the whole layout.
 *
 * Structure only. Whether a `panelKind` is *registered* is deliberately not
 * checked here: an unknown kind is a pane the renderer hides, never an illegal
 * tree. Treating it as illegal would mean uninstalling one surface resets the
 * person's entire arrangement.
 */
export function validateLayout(input: Layout): ValidateResult {
  if (!isRecord(input)) return { ok: false, reason: 'layout is not an object' }
  if (input.schemaVersion !== LAYOUT_SCHEMA_VERSION) {
    return { ok: false, reason: `schemaVersion must be ${LAYOUT_SCHEMA_VERSION}` }
  }
  if (!Array.isArray(input.float) || input.float.length !== 0) {
    return { ok: false, reason: 'float must be an empty array in v1' }
  }

  const sidebar = input.sidebar as unknown
  if (!isRecord(sidebar) || sidebar.type !== 'pane') return { ok: false, reason: 'sidebar must be a pane' }
  if (sidebar.panelKind !== 'nav-sidebar') return { ok: false, reason: 'sidebar must be nav-sidebar' }
  if (sidebar.edge !== 'left') return { ok: false, reason: "sidebar edge must be 'left' in v1" }
  if (!isValidId(sidebar.id)) return { ok: false, reason: 'sidebar id invalid' }

  const ids = new Set<string>([sidebar.id as string])
  const contentPanes: PaneNode[] = []
  const shape = validateNodeShape(input.content, 1, ids, contentPanes)
  if (!shape.ok) return shape

  const mains = contentPanes.filter((p) => p.panelKind === 'main')
  if (mains.length !== 1) {
    return { ok: false, reason: `content must contain exactly one main pane (got ${mains.length})` }
  }
  if (mains[0]?.collapsed === true) return { ok: false, reason: 'the main pane must not be collapsed' }
  if (contentPanes.some((p) => p.panelKind === 'nav-sidebar')) {
    return { ok: false, reason: 'nav-sidebar must stay outside the content tree' }
  }
  return { ok: true }
}

/**
 * Turn untrusted data — a file on disk, an IPC argument — into a layout that is
 * necessarily legal. Any failure falls back to the default and reports why;
 * nothing throws. This is what makes "the layout file got corrupted, restarting
 * fixed it" true rather than aspirational.
 */
export function coerceLayout(raw: unknown): CoerceResult {
  if (!isRecord(raw)) return { layout: createDefaultLayout(), fallback: true, reason: 'not an object' }
  let cloned: Layout
  try {
    cloned = structuredClone(raw) as Layout
  } catch {
    return { layout: createDefaultLayout(), fallback: true, reason: 'not cloneable' }
  }
  const v = validateLayout(cloned)
  if (!v.ok) return { layout: createDefaultLayout(), fallback: true, reason: v.reason }
  return { layout: cloned, fallback: false }
}

// ---------------------------------------------------------------------------
// Operations — immutable; an illegal one returns the original by reference
// ---------------------------------------------------------------------------

/**
 * Every operation ends here, so no operation can produce an illegal tree. An
 * op that would break an invariant is rejected whole rather than landing
 * half-applied.
 */
function finishOp(original: Layout, mutated: Layout, reason: string): LayoutOpResult {
  const v = validateLayout(mutated)
  if (!v.ok) return { layout: original, applied: false, reason: `${reason}: ${v.reason}` }
  return { layout: mutated, applied: true }
}

/** Collapse or expand a pane. The main pane refuses, via the exit check. */
export function setPaneCollapsed(layout: Layout, paneId: string, collapsed: boolean): LayoutOpResult {
  if (!findPaneById(layout, paneId)) {
    return { layout, applied: false, reason: `pane not found: ${paneId}` }
  }
  const next = structuredClone(layout)
  for (const pane of walkPanes(next)) {
    if (pane.id === paneId) pane.collapsed = collapsed
  }
  return finishOp(layout, next, 'setPaneCollapsed rejected')
}

/**
 * Resize one child of a split, redistributing the remainder across its
 * siblings in proportion to what they already held.
 */
export function setSplitChildFraction(
  layout: Layout,
  splitId: string,
  childIndex: number,
  fraction: number,
): LayoutOpResult {
  if (!(Number.isFinite(fraction) && fraction > 0 && fraction < 1)) {
    return { layout, applied: false, reason: 'fraction must be between 0 and 1 (exclusive)' }
  }
  if (!Number.isInteger(childIndex)) {
    return { layout, applied: false, reason: `child index must be an integer: ${childIndex}` }
  }
  const next = structuredClone(layout)
  const split = findSplitById(next.content, splitId)
  if (!split) return { layout, applied: false, reason: `split not found: ${splitId}` }
  if (childIndex < 0 || childIndex >= split.children.length) {
    return { layout, applied: false, reason: `child index out of range: ${childIndex}` }
  }

  const siblings = split.children
  const target = siblings[childIndex]
  if (!target) return { layout, applied: false, reason: `child missing at ${childIndex}` }

  // A transfer that would starve any sibling is refused entirely, not clamped:
  // clamping mid-drag makes the pointer and the edge disagree, which reads as
  // the panel fighting back.
  const remainder = 1 - fraction
  if (remainder < MIN_SPLIT_CHILD_FRACTION * (siblings.length - 1) - FRACTION_TOLERANCE) {
    return { layout, applied: false, reason: 'transfer would starve a sibling' }
  }
  if (fraction < MIN_SPLIT_CHILD_FRACTION - FRACTION_TOLERANCE) {
    return { layout, applied: false, reason: 'target would fall below the minimum share' }
  }

  const siblingSum = siblings.reduce((acc, c, i) => acc + (i === childIndex ? 0 : c.fraction), 0)
  target.fraction = fraction
  for (let i = 0; i < siblings.length; i++) {
    if (i === childIndex) continue
    const sibling = siblings[i]
    if (!sibling) continue
    sibling.fraction =
      siblingSum > 0 ? (sibling.fraction / siblingSum) * remainder : remainder / (siblings.length - 1)
  }
  normalizeSplitFractions(split)
  return finishOp(layout, next, 'setSplitChildFraction rejected')
}

/**
 * Dock a new panel in the content root — how a surface arrives.
 *
 * The new pane takes `fraction` of the width, clamped, and the existing
 * children give it up proportionally. An out-of-range index appends.
 */
export function insertRootSplitPane(
  layout: Layout,
  pane: { id: string; panelKind: PanelKind; minWidth?: number },
  fraction = 0.25,
  index = Number.MAX_SAFE_INTEGER,
): LayoutOpResult {
  if (layout.content.type !== 'split') {
    return { layout, applied: false, reason: 'content root is a single pane; nothing to insert beside' }
  }
  const next = structuredClone(layout)
  const root = next.content as SplitNode

  const share = Math.min(0.8, Math.max(MIN_SPLIT_CHILD_FRACTION, fraction))
  for (const child of root.children) child.fraction *= 1 - share

  const at = Math.max(0, Math.min(root.children.length, index))
  root.children.splice(at, 0, {
    fraction: share,
    node: {
      type: 'pane',
      id: pane.id,
      panelKind: pane.panelKind,
      ...(pane.minWidth !== undefined ? { minWidth: pane.minWidth } : {}),
    },
  })
  normalizeSplitFractions(root)
  return finishOp(layout, next, 'insertRootSplitPane rejected')
}

/** Undock the first pane of a kind from the content root. */
export function removeRootSplitPaneByKind(layout: Layout, kind: PanelKind): LayoutOpResult {
  if (layout.content.type !== 'split') {
    return { layout, applied: false, reason: 'content root is a single pane' }
  }
  const next = structuredClone(layout)
  const root = next.content as SplitNode
  const at = root.children.findIndex((c) => c.node.type === 'pane' && c.node.panelKind === kind)
  if (at === -1) return { layout, applied: false, reason: `no root pane of kind ${kind}` }
  if (root.children.length <= 2) {
    return { layout, applied: false, reason: 'a split needs at least two children' }
  }
  root.children.splice(at, 1)
  normalizeSplitFractions(root)
  return finishOp(layout, next, 'removeRootSplitPaneByKind rejected')
}
