/**
 * The main window's layout, as a tree.
 *
 * Fleet's shell could only ever express one thing: a navigation state that
 * shows a list. `AppShell.tsx` grew to 4,000 lines of
 * `if (isSourcesNavigation) … if (isSkillsNavigation) …`, each branch naming a
 * concrete surface, and `PanelStackContainer` derived its panels from the
 * route. Every new surface therefore had to become a navigation state plus a
 * sidebar row — which is why asking for an infinite canvas kept producing
 * another second-level page.
 *
 * This is the seam that was missing. A layout is a tree of panes; a pane says
 * only which `panelKind` it hosts; a registry maps kind to component. The
 * engine never learns who the panels are. Adding the canvas, the browser, the
 * document editor or the video timeline is one registry entry and one pane —
 * the engine does not change, and neither does this file.
 *
 * It lives in `shared` because the renderer draws the tree and the main process
 * validates it before writing it to disk. Two implementations of "is this
 * layout legal" would drift, and the one that drifts is the one that lets a
 * corrupt file through.
 *
 * Zero dependencies, zero IO, every function pure, no input ever mutated, and
 * nothing here throws — a damaged layout coerces back to the default instead.
 * That is what makes "the file got corrupted, restart fixed it" true.
 *
 * The model follows Cindy's `shared/layoutTree.ts` (Apache-2.0), which solved
 * this problem first; see `docs/references/REFERENCE-REGISTRY.md`.
 */

/** Schema version of a persisted layout. Bump only with a migration. */
export const LAYOUT_SCHEMA_VERSION = 1 as const

/**
 * Maximum depth of the split tree, leaves included. A corrupt or hostile file
 * must not be able to blow the render stack.
 */
export const MAX_TREE_DEPTH = 8

/** Longest accepted `panelKind`. Anything longer is treated as corruption. */
const MAX_PANEL_KIND_LENGTH = 128

/**
 * Smallest share a split child may hold. A resize that would push a sibling
 * below this is rejected whole rather than clamped, so a drag either lands or
 * springs back — it never silently produces a pane too narrow to use.
 */
export const MIN_SPLIT_CHILD_FRACTION = 0.05

/**
 * Comparison slack for fractions. A caller that clamps to the floor computes a
 * value carrying float residue (`0.4589135 - 0.05` added back is
 * `0.04999999999999999`), and a bare `< 0.05` test would reject the very
 * transfer that was clamped correctly — the drag would spring back at exactly
 * the boundary the clamp was meant to reach.
 */
const FRACTION_TOLERANCE = 1e-9

/**
 * The panes Fleet ships. Everything else — the production surfaces, plugin
 * panels — arrives through the open namespace below.
 */
export const BUILTIN_PANEL_KINDS = ['nav-sidebar', 'navigator', 'main', 'workbench'] as const
export type BuiltinPanelKind = (typeof BUILTIN_PANEL_KINDS)[number]

/**
 * A panel's identity.
 *
 * Deliberately an open namespace — any non-empty string — rather than a closed
 * union, and the reason is what happens when a kind is *not* recognised. A
 * surface that is not installed, or a kind added by a newer version, must leave
 * the tree **legal**: the renderer hides that pane and reflows the space, and
 * the pane comes back where it was when the surface returns. If an unknown kind
 * invalidated the tree instead, uninstalling one plugin would destroy the
 * person's entire layout.
 *
 * `(string & {})` keeps editor completion for the builtin names while accepting
 * any string.
 */
export type PanelKind = BuiltinPanelKind | (string & {})

/** A leaf: one docking position holding one panel. */
export type PaneNode = {
  type: 'pane'
  /** Unique within the layout. Generated by the caller — this layer stays deterministic. */
  id: string
  panelKind: PanelKind
  /**
   * Collapsed state. Whether a pane *may* collapse depends on it being against
   * an edge, which only the renderer knows; this field carries the state alone.
   */
  collapsed?: boolean
  /** Minimum width in px. */
  minWidth?: number
}

/** A cut in one direction. Each child's `fraction` is its share along that axis. */
export type SplitNode = {
  type: 'split'
  id: string
  /** `row` lays children out horizontally; `column` stacks them. */
  direction: 'row' | 'column'
  children: { fraction: number; node: LayoutNode }[]
}

export type LayoutNode = PaneNode | SplitNode

/** A free-floating panel. Reserved: v1 keeps this empty. */
export type FloatPanel = {
  id: string
  panelKind: PanelKind
  x: number
  y: number
  width: number
  height: number
}

/**
 * One layout for the window. It does not vary per session: panel *contents*
 * follow the session, the arrangement does not.
 */
export type Layout = {
  schemaVersion: typeof LAYOUT_SCHEMA_VERSION
  /**
   * The nav sidebar: a full-height column outside the tree, so no split inside
   * the content area can ever cut through it.
   */
  sidebar: PaneNode & { edge: 'left' }
  /** The content area. */
  content: LayoutNode
  /** Empty in v1. */
  float: FloatPanel[]
}

/** `ok: false` names the first violation — for logs, not for the person. */
export type ValidateResult = { ok: true } | { ok: false; reason: string }

/** `fallback: true` means the input was unusable and the default was returned. */
export type CoerceResult = { layout: Layout; fallback: boolean; reason?: string }

/** `applied: false` returns the original layout by reference, unchanged. */
export type LayoutOpResult = { layout: Layout; applied: boolean; reason?: string }

// ---------------------------------------------------------------------------
// Default
// ---------------------------------------------------------------------------

/**
 * The arrangement Fleet has today: the nav sidebar outside the tree, then the
 * navigator list, the main surface and the workbench side by side. The default
 * must reproduce what the person already sees, so mounting the engine changes
 * nothing visually on first run.
 */
export function createDefaultLayout(): Layout {
  return {
    schemaVersion: LAYOUT_SCHEMA_VERSION,
    sidebar: { type: 'pane', id: 'sidebar', panelKind: 'nav-sidebar', edge: 'left' },
    content: {
      type: 'split',
      id: 'root',
      direction: 'row',
      children: [
        { fraction: 0.24, node: { type: 'pane', id: 'navigator', panelKind: 'navigator', minWidth: 240 } },
        { fraction: 0.46, node: { type: 'pane', id: 'main', panelKind: 'main', minWidth: 400 } },
        { fraction: 0.3, node: { type: 'pane', id: 'workbench', panelKind: 'workbench', minWidth: 280 } },
      ],
    },
    float: [],
  }
}

// ---------------------------------------------------------------------------
// Guards and traversal
// ---------------------------------------------------------------------------

export function isPaneNode(node: LayoutNode): node is PaneNode {
  return node.type === 'pane'
}

export function isSplitNode(node: LayoutNode): node is SplitNode {
  return node.type === 'split'
}

function walkContentPanes(node: LayoutNode, out: PaneNode[]): void {
  if (node.type === 'pane') {
    out.push(node)
    return
  }
  for (const child of node.children) walkContentPanes(child.node, out)
}

/** Every pane: sidebar first, then the content tree depth-first, then floats. */
export function walkPanes(layout: Layout): PaneNode[] {
  const out: PaneNode[] = [layout.sidebar]
  walkContentPanes(layout.content, out)
  for (const f of layout.float) out.push({ type: 'pane', id: f.id, panelKind: f.panelKind })
  return out
}

export function findPaneById(layout: Layout, paneId: string): PaneNode | null {
  return walkPanes(layout).find((p) => p.id === paneId) ?? null
}

export function countPanelKind(layout: Layout, kind: PanelKind): number {
  return walkPanes(layout).filter((p) => p.panelKind === kind).length
}

/** Where a pane sits inside a split, for reading and writing its share. */
export interface SplitChildRef {
  splitId: string
  childIndex: number
  fraction: number
}

function findSplitChildByKindIn(node: LayoutNode, kind: PanelKind): SplitChildRef | null {
  if (node.type !== 'split') return null
  for (let i = 0; i < node.children.length; i++) {
    const child = node.children[i]
    if (!child) continue
    if (child.node.type === 'pane' && child.node.panelKind === kind) {
      return { splitId: node.id, childIndex: i, fraction: child.fraction }
    }
    const nested = findSplitChildByKindIn(child.node, kind)
    if (nested) return nested
  }
  return null
}

/**
 * Locate a panel by kind rather than by position, so a consumer that resizes
 * "the workbench" keeps working after the person moves it to the other side.
 */
export function findSplitChildByPanelKind(layout: Layout, kind: PanelKind): SplitChildRef | null {
  return findSplitChildByKindIn(layout.content, kind)
}

function findSplitById(node: LayoutNode, splitId: string): SplitNode | null {
  if (node.type !== 'split') return null
  if (node.id === splitId) return node
  for (const child of node.children) {
    const found = findSplitById(child.node, splitId)
    if (found) return found
  }
  return null
}

/** Rescale a split's children so the shares sum to exactly 1. */
function normalizeSplitFractions(split: SplitNode): void {
  const sum = split.children.reduce((acc, c) => acc + c.fraction, 0)
  if (sum <= 0) {
    const even = 1 / split.children.length
    for (const child of split.children) child.fraction = even
    return
  }
  for (const child of split.children) child.fraction = child.fraction / sum
}
