#!/usr/bin/env python3
"""Keep each docs/modules/*.md card in step with the capability register.

The card is the first thing a module document shows: which register rows it owns, their status,
release and surfaces. It is derived, never hand-edited, so a status change in the register cannot
leave a stale copy in a module. Feature modules own the rows whose Loop column names them; release
slice modules (baseline, shell, services) collect the rows anchored to their release.

  python3 scripts/module_cards.py          # rewrite the cards
  python3 scripts/module_cards.py --check  # exit 1 if any card is stale (run by the commit gate)
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BEGIN = '<!-- module-card: generated by scripts/module_cards.py from the capability register; do not edit -->'
END = '<!-- /module-card -->'
SLICES = {'baseline.md': 'R0', 'shell.md': 'R1', 'services.md': 'R2'}
ROW = re.compile(r'^\| ((?:CORE|INFO|EXEC|INTEL|CREATE|ORCH)-\d{2}) \|', re.M)


def register_rows(root: Path) -> list[list[str]]:
    text = (root / 'docs/capabilities.md').read_text(encoding='utf-8')
    body = text.split('## Capability register\n', 1)[1].split('\n## ', 1)[0]
    return [[c.strip() for c in line.split('|')][1:-1] for line in body.splitlines() if ROW.match(line)]


def card(name: str, rows: list[list[str]]) -> str:
    release = SLICES.get(name)
    if release:
        owned = [r for r in rows if re.search(rf'\b{release}\b', r[7].split('/', 1)[0])]
        rule = f'register rows anchored to {release}'
    else:
        owned = [r for r in rows if r[5] == f'modules/{name}']
        rule = f'register rows whose loop is this module'
    lines = [BEGIN, '## Module card', '',
             f'{len(owned)} {rule} ([register](../capabilities.md#capability-register)). '
             'Status is the register\'s; change it there, then run `python3 scripts/module_cards.py`.', '']
    if owned:
        lines += ['| ID | Capability | Status | Release / acceptance | Surfaces |', '|---|---|---|---|---|']
        lines += [f'| {r[0]} | {r[1]} | {r[4]} | {r[7]} | {r[6]} |' for r in owned]
    else:
        lines.append('No register row yet.')
    return '\n'.join(lines + [END])


def expected(path: Path, rows: list[list[str]]) -> str:
    text = path.read_text(encoding='utf-8')
    block = card(path.name, rows)
    if BEGIN in text:
        return re.sub(re.escape(BEGIN) + r'.*?' + re.escape(END), lambda _: block, text, flags=re.S)
    # First placement: after the title and its lead paragraphs, before the first section.
    head, sep, rest = text.partition('\n## ')
    return f'{head.rstrip()}\n\n{block}\n\n## {rest}' if sep else f'{text.rstrip()}\n\n{block}\n'


def stale_cards(root: Path) -> list[str]:
    rows = register_rows(root)
    return [str(p.relative_to(root)) for p in sorted((root / 'docs/modules').glob('*.md'))
            if p.read_text(encoding='utf-8') != expected(p, rows)]


def main() -> int:
    if '--check' in sys.argv:
        stale = stale_cards(ROOT)
        for path in stale:
            print(f'stale module card: {path} (run python3 scripts/module_cards.py)')
        return 1 if stale else 0
    rows = register_rows(ROOT)
    for path in sorted((ROOT / 'docs/modules').glob('*.md')):
        path.write_text(expected(path, rows), encoding='utf-8')
    return 0


if __name__ == '__main__':
    sys.exit(main())
