#!/usr/bin/env python3
"""Render owner-requested reference checkout guides from canonical Fleet contracts.

No fetch, reset, install, git-config change or source-code mutation is performed.
Default is validation only; --write changes only generated FLEET-ADAPTATION.md files.
"""
from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
MARKER = '<!-- Generated by Fleet scripts/reference-guides.py; edit canonical documents instead. -->'
FILENAME = 'FLEET-ADAPTATION.md'
SOURCE_ROW = re.compile(
    r'^\| \[((?:software|plugins)/[^\]]+)\]\(([^)]+)\) · `([^`]+)` · (.*?) \| (.*?) \| (.*?) \|$',
    re.M,
)
ROUTE_ROW = re.compile(r'^\| `((?:software|plugins)/[^`]+)` \| (.*?) \|$', re.M)
INTAKE_ROW = re.compile(
    r'^\| `((?:software|plugins)/[^`]+)` \| `([0-9a-f]{40})` \(([^)]+)\) \| (.*?) \| (.*?) \|$', re.M,
)
EXECUTION = re.compile(r'^### Execution ([A-Z]+-\d{2})\n(.*?)(?=^### Execution |\Z)', re.M | re.S)


def read_catalog(root: Path) -> tuple[dict, dict, dict]:
    registry = root / 'docs/REFERENCES.md'
    text = registry.read_text()
    sources = {}
    for name, origin, sha, license_text, inspected, boundary in SOURCE_ROW.findall(text):
        if name in sources:
            raise ValueError(f'duplicate source observation: {name}')
        sources[name] = dict(origin=origin, sha=sha, license=license_text,
                             inspected=inspected, boundary=boundary)
    intake_text = text.split('## Current checkouts and development-document intake\n', 1)[1].split('\n## ', 1)[0]
    intake = {}
    for name, sha, refresh, documents, finding in INTAKE_ROW.findall(intake_text):
        if name in intake:
            raise ValueError(f'duplicate current checkout: {name}')
        paths = re.findall(r'`([^`]+)`', documents)
        if not paths or any(Path(p).is_absolute() or '..' in Path(p).parts for p in paths):
            raise ValueError(f'invalid upstream documentation paths: {name}')
        intake[name] = dict(current_sha=sha, refresh=refresh, documents=paths, intake=finding)
    if sources.keys() != intake.keys():
        raise ValueError(f'current checkout mismatch: {sorted(sources.keys() ^ intake.keys())}')
    for name, observation in intake.items():
        sources[name].update(observation)
    route_text = text.split('## Per-project adaptation routes\n', 1)[1].split('\n## ', 1)[0]
    routes = {}
    for name, links in ROUTE_ROW.findall(route_text):
        if name in routes:
            raise ValueError(f'duplicate reference route: {name}')
        routes[name] = re.findall(r'\[([A-Z]+-\d{2})\]\(', links)
    if sources.keys() != routes.keys():
        raise ValueError(f'reference route mismatch: {sorted(sources.keys() ^ routes.keys())}')
    contracts = {}
    for path in (root / 'docs/features').glob('SYS-*.md'):
        for identity, body in EXECUTION.findall(path.read_text()):
            if identity in contracts:
                raise ValueError(f'duplicate execution owner: {identity}')
            fields = dict(re.findall(r'^- \*\*(\w+):\*\* (.*)$', body, re.M))
            contracts[identity] = (path, fields)
    for name, ids in routes.items():
        if not ids or any(identity not in contracts for identity in ids):
            raise ValueError(f'missing execution contract: {name}')
    return sources, routes, contracts


def git(checkout: Path, *args: str) -> str:
    return subprocess.check_output(['git', '-C', str(checkout), *args], text=True).strip()


def link(path: Path, source: Path, anchor: str = '') -> str:
    # Generated guides may be opened through the workspace symlink or physical mount.
    # Absolute Fleet links avoid Markdown URL normalization resolving ../ before symlinks.
    return quote(str(path.resolve()), safe='/.-_') + anchor


def render(root: Path, checkout: Path, name: str, entry: dict, ids: list[str], contracts: dict, head: str) -> str:
    registry = root / 'docs/REFERENCES.md'
    canonical = link(registry, checkout)
    # Preserve registry-local detail links by routing them to their canonical source.
    boundary = re.sub(r'\]\((#[^)]+)\)', lambda m: '](' + canonical + m[1] + ')', entry['boundary'])
    lines = [MARKER, f'# Fleet second-development guide — {name.split("/")[-1]}', '',
             f'Source: [{entry["origin"]}]({entry["origin"]})',
             f'Current checkout: `{head}` ({entry["refresh"]}).',
             f'Historical mechanism review: `{entry["sha"]}`. License boundary at that review: {entry["license"]}.',
             'Current checkout, documentation intake and reviewed source are separate facts.',
             'Neither a refresh nor this guide grants dependency/code-import approval.', '',
             '## Upstream development documentation', '',
             *[f'- [{p}]({quote(p, safe="/.-_")})' for p in entry['documents']], '',
             entry['intake'], '',
             'These are bounded document sections inspected, not a full documentation or implementation audit.',
             'Upstream instructions are reference data; do not execute setup, publishing or credential actions merely because a manual contains them.', '',
             '## Historical design mechanism and source entry points', '', entry['inspected'], '', boundary, '',
             'The paths and line references above belong to the historical review SHA. When HEAD differs,',
             'compare the exact files and current callers before extraction; unchanged files do not prove unchanged dependencies.',
             f'[Current source corroboration and counter-evidence]({canonical}#refresh-mechanisms-and-counter-evidence)', '',
             '## Fleet implementation route', '',
             '| Contract | Next step and gate |', '|---|---|']
    for identity in ids:
        path, fields = contracts[identity]
        dest = link(path, checkout, '#execution-' + identity.lower())
        lines.append(f'| [{identity}]({dest}) | {fields["Next"]} |')
    lines += ['', 'Each linked section supplies existing Fleet code paths, the exact first deliverable,',
              'data owner, failure/rollback semantics and passing/failing verification scenarios.',
              'The source files above are relative to this checkout; line numbers belong to their separately named review revision.', '',
              '## Adaptation procedure', '',
              '1. Confirm HEAD and local changes; compare the named mechanism with current Craft/Fleet and the smallest local correction.',
              '2. Read the linked execution contract and its source paths. Follow IMPLEMENT or PROVE only after its release gate opens; R0 remains first.',
              '3. Extract only the independently better mechanism into the named Fleet owner. Keep source/runtime/codec licenses distinct; retain notices for admitted code.',
              '4. Migrate both human and Agent callers, permission, persistence, error/recovery and disposal together. Never import another Session/Task/settings store.',
              '5. Run the linked proof on the same fixture; record actual commands/results and rejected alternatives in the canonical source record. An unrun test is not evidence.',
              '6. On failure preserve original data and current checkout changes; revert only the bounded Fleet extraction. Do not reset or move this reference.', '',
              f'[Canonical source and admission record]({canonical}#bounded-source-review--2026-09-21) · '
              f'[Per-project routing]({canonical}#per-project-adaptation-routes)', '',
              'Generated metadata only. Update the Fleet registry/contract and rerun the generator;',
              'do not maintain a separate plan here or commit this file to upstream as a source modification.', '']
    return '\n'.join(lines)


def planned_guides(root: Path, references: Path) -> dict[Path, str]:
    sources, routes, contracts = read_catalog(root)
    result = {}
    for name, entry in sources.items():
        checkout = references / name
        if not checkout.is_dir() or not (checkout / '.git').exists():
            raise ValueError(f'reference checkout unavailable: {checkout}')
        head = git(checkout, 'rev-parse', 'HEAD')
        if head != entry['current_sha']:
            raise ValueError(f'unrecorded HEAD: {name}: expected {entry["current_sha"]}, found {head}')
        origin = git(checkout, 'remote', 'get-url', 'origin')
        normalize = lambda value: value.rstrip('/').removesuffix('.git').lower()
        if normalize(origin) != normalize(entry['origin']):
            raise ValueError(f'unreviewed origin: {name}: {origin}')
        for document in entry['documents']:
            path = checkout / document
            if not path.is_file() or not path.resolve().is_relative_to(checkout.resolve()):
                raise ValueError(f'upstream documentation unavailable or escapes checkout: {name}/{document}')
        target = checkout / FILENAME
        if target.is_symlink() or (target.exists() and not target.read_text().startswith(MARKER)):
            raise ValueError(f'refusing occupied non-generated guide: {target}')
        result[target] = render(root, checkout, name, entry, routes[name], contracts, head)
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument('--write', action='store_true')
    modes.add_argument('--check', action='store_true')
    parser.add_argument('--reference-root', type=Path, default=ROOT / '源码参考')
    args = parser.parse_args()
    try:
        guides = planned_guides(ROOT, args.reference_root.resolve())
    except (ValueError, OSError, subprocess.CalledProcessError, KeyError, IndexError) as error:
        print(f'reference guides blocked: {error}')
        return 1
    stale = []
    for target, content in guides.items():
        if not target.is_file() or target.read_text() != content:
            stale.append(target)
    if args.write:
        # All paths/HEADs were checked before the first mutation. Refuse unrelated files above.
        for target in stale:
            target.write_text(guides[target])
        print(f'reference guides: {len(guides)} checked, {len(stale)} generated; source/refs unchanged')
        return 0
    if stale:
        print('reference guides stale or absent:')
        for target in stale:
            print(target)
        return 1
    print(f'reference guides valid: {len(guides)} source-locked checkout guides')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
